# Generated by Django 3.2.9 on 2021-12-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='author',
            new_name='user',
        ),
    ]
