# Generated by Django 3.2.9 on 2021-12-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_author_bookmark_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='author',
        ),
    ]
