# Generated by Django 3.2.9 on 2021-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='week_views',
            field=models.IntegerField(default=0),
        ),
    ]
