# Generated by Django 3.2.9 on 2021-12-02 14:04

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_week_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=blog.models.upload_to, verbose_name='Image')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postarray', to='blog.post')),
            ],
        ),
    ]
