# Generated by Django 3.2.9 on 2021-12-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_postarray_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarray',
            name='post',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.postarray'),
        ),
        migrations.AlterField(
            model_name='postarray',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
