# Generated by Django 3.2.9 on 2021-12-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_postarray_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarray',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='postarray', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postarray',
            name='text',
            field=models.TextField(),
        ),
    ]
