# Generated by Django 3.2.9 on 2021-12-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20211204_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='count',
        ),
    ]
