# Generated by Django 3.2.9 on 2021-12-04 15:35

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_content_post_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('image', models.ImageField(default='posts/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.mockup'),
        ),
    ]
