# Generated by Django 3.2.9 on 2021-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211204_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Mockup',
        ),
    ]
